port: 8080
admin_port: 8081
algorithm: least-response-time

services:
  - name: Desktops
    host: desktop.krogsveen.org
    path: ""
    backends:
      - url: http://193.75.49.222
        weight: 5
        max_connections: 1000

  - name: SEQ
    path: "/api"
    backends:
      - url: http://193.75.49.178
        weight: 5
        max_connections: 1000

  - name: api2
    path: "/api3/"
    backends:
      - url: http://localhost:8088
        weight: 5
        max_connections: 1000

      - url: http://localhost:8089
        weight: 3
        max_connections: 800

health_check:
  interval: 10s
  timeout: 2s
  path: /health

auth:
  enabled: true
  api_key: mySecretKey

admin_api:
  rate_limit:
    requests_per_second: 10
    burst: 20

rate_limit:
  requests_per_second: 100
  burst: 150

connection_pool:
  max_idle: 100
  max_open: 1000
  idle_timeout: 90s
