port: 443
admin_port: 4433

services:
  - name: backend-api
    host: internal-api1.local.com
    locations:
      - path: "/api/"
        lb_policy: round-robin
        backends:
          - url: http://internal-api1.local.com:8455
            weight: 5
            max_connections: 1000
          - url: http://internal-api2.local.com:8455
            weight: 3
            max_connections: 800

  - name: frontend
    host: frontend.local.com
    locations:
      - path: ""
        lb_policy: least_connections
        backends:
          - url: http://frontend-1.local.com:3000
            weight: 5
            max_connections: 1000

          - url: http://frontend-2.local.com:3000
            weight: 3
            max_connections: 800

health_check:
  interval: 10s
  timeout: 2s
  path: /health

auth:
  enabled: true
  api_key: mySecretKey

admin_api:
  rate_limit:
    requests_per_second: 10
    burst: 20

rate_limit:
  requests_per_second: 100
  burst: 150

connection_pool:
  max_idle: 100
  max_open: 1000
  idle_timeout: 90s
