port: 8080
admin_port: 8081
algorithm: least-response-time

services:
  - name: api1
    path: "/api1/"
    backends:
      - url: http://localhost:8081
        weight: 5
        max_connections: 1000

      - url: http://localhost:8082
        weight: 3
        max_connections: 800
  - name: api2
    path: "/api2/"
    backends:
      - url: http://localhost:8083
        weight: 5
        max_connections: 1000

      - url: http://localhost:8084
        weight: 3
        max_connections: 800

health_check:
  interval: 10s
  timeout: 2s
  path: /health

auth:
  enabled: true
  api_key: mySecretKey

admin_api:
  rate_limit:
    requests_per_second: 10
    burst: 20

rate_limit:
  requests_per_second: 100
  burst: 150

connection_pool:
  max_idle: 100
  max_open: 1000
  idle_timeout: 90s
